#!/bin/sh

curl -sL http://cpanmin.us | perl - -L local --quiet --notest App::cpanminus local::lib
eval $(perl -Ilocal/lib/perl5 -Mlocal::lib=local)

git clone git@github.com:rakudo/rakudo.git
cd rakudo
perl Configure.pl --gen-nqp --backends=jvm
make
rm -rf nqp
cd ..
tar cvzf rakudo.tar.gz `find rakudo -name \*.jar`
tar avzf rakudo.tar.gz rakudo/perl6

cpanm -L local --notest --quiet Net::Amazon::S3
curl -sLo s3put.pl https://raw.github.com/pnu/heroku-vendor-cpanfile/master/s3put.pl
chmod +x s3put.pl
./s3put.pl rakudo.tar.gz

